### ISSUE TITLE
[Bug] index.list() error message for non-serverless indexes is unclear

### ISSUE THREAD

**Issue by shamussim-ai** [pinecone-io/python-sdk#331]
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I followed the code exactly from the documentation

```Python
from pinecone import Pinecone

pc = Pinecone(api_key='34zzzzzzzzzz')
index = pc.Index('self-retriever-pae')

# To iterate over all result pages using a generator function
for ids in index.list( namespace="Non_Varicea"):
    print(ids)
```

This succeeds (as expected) against a serverless index, but when run on a pod-based index (which indeed does not support `list()`) an unclear error message is returned:

```Python
PineconeApiTypeError: Invalid type for variable 'received_data'. Required value type is ListResponse and passed type was str at ['received_data']
```

### Expected Behavior

When run on a non-serverless index (which do not support `list()`) a clear error message that this is an unsupported operation should be displayed.

### Steps To Reproduce

Run code using env specified

Code

```Python
from pinecone import Pinecone

pc = Pinecone(api_key='34zzzzzzzzzz')
index = pc.Index('self-retriever-pae')

# To iterate over all result pages using a generator function
for ids in index.list( namespace="Non_Varicea"):
    print(ids)
```

### Relevant log output

```shell
PineconeApiTypeError                      Traceback (most recent call last)
[<ipython-input-10-ccee60efe570>](https://localhost:8080/#) in <cell line: 8>()
      6 
      7 # To iterate over all result pages using a generator function
----> 8 for ids in index.list( namespace="Non_Variceal_hi_res"):
      9     print(ids)

10 frames
[/usr/local/lib/python3.10/dist-packages/pinecone/core/client/model_utils.py](https://localhost:8080/#) in attempt_convert_item(input_value, valid_classes, path_to_item, configuration, spec_property_naming, key_type, must_convert, check_type)
   1419         if configuration is None or not configuration.discard_unknown_keys:
   1420             raise get_type_error(input_value, path_to_item, valid_classes,
-> 1421                                  key_type=key_type)
   1422     for valid_class in valid_classes_coercible:
   1423         try:

PineconeApiTypeError: Invalid type for variable 'received_data'. Required value type is ListResponse and passed type was str at ['received_data']
```

### Environment

```markdown
- OS:Windows
- Python:3.11
- pinecone: 3.0.03
```

### Additional Context

none

**Comment by volksport** [comment]
Can confirm this is also an issue for us

**Comment by shamussim-ai** [comment]
Hi there, any updates on this? Thank you

**Comment by daverigby** [comment]
I attempted to reproduce this on the latest version (v4.0.0) on macOS and don't see the problem anymore.

**Comment by cbelsole** [comment]
@daverigby I finally figured out why this was not working. This only works for a serverless index. The error message could probably be clearer.

**Comment by daverigby** [comment]
> @daverigby I finally figured out why this was not working. This only works for a serverless index. The error message could probably be clearer.

Thanks @cbelsole . I'll re-open and change to cover the fact that the error is not clear for non-server less indexes.

**Comment by gildemberg-santos** [comment]
Also occurring in version 5.3.1


```
RetryError[<Future at 0x3ee6ff794dc0 state=finished raised AttributeError>]

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/code/vector_store/providers/pinecone_vectorstore.py", line 150, in delete
    return self._delete_by_ids(ids)
  File "/code/vector_store/providers/pinecone_vectorstore.py", line 189, in _delete_by_ids
    raise e
  File "/code/vector_store/providers/pinecone_vectorstore.py", line 183, in _delete_by_ids
    ids_to_delete = list(self.index.list(prefix=id, limit=100))
  File "/usr/local/lib/python3.10/site-packages/pinecone/data/index.py", line 621, in list
    if len(results.vectors) > 0:
AttributeError: 'str' object has no attribute 'vectors'




```

**Comment by brysonwxx** [comment]
hi, I also encounter the same error

**Comment by brysonwxx** [comment]
> hi, I also encounter the same error. @daverigby @volksport python: 3.8.10 pinecone-client: 5.0.1 when I create an Pinecone instance: `self.pc_cli = Pinecone(api_key=self.api_key, host=self.host, pool_threads=self.POOL_THREADS)`
> 
> and call the functions: `self.pc_cli.describe_index(collection_name)`, or `r = self.pc_cli.list_indexes()`,
> 
> it raises the error:
> 
> `File "/home/ubuntu/.pyenv/versions/3.8.10/envs/xxx/lib/python3.8/site-packages/pinecone/control/pinecone.py", line 541, in describe_index description = api_instance.describe_index(name) File "/home/ubuntu/.pyenv/versions/3.8.10/envs/xxx/lib/python3.8/site-packages/pinecone/core/openapi/shared/api_client.py", line 761, in __call__ return self.callable(self, *args, **kwargs) File "/home/ubuntu/.pyenv/versions/3.8.10/envs/xxx/lib/python3.8/site-packages/pinecone/core/openapi/control/api/manage_indexes_api.py", line 632, in __describe_index return self.call_with_http_info(**kwargs) File "/home/ubuntu/.pyenv/versions/3.8.10/envs/xxx/lib/python3.8/site-packages/pinecone/core/openapi/shared/api_client.py", line 819, in call_with_http_info return self.api_client.call_api( File "/home/ubuntu/.pyenv/versions/3.8.10/envs/xxx/lib/python3.8/site-packages/pinecone/core/openapi/shared/api_client.py", line 380, in call_api return self.__call_api( File "/home/ubuntu/.pyenv/versions/3.8.10/envs/xxx/lib/python3.8/site-packages/pinecone/core/openapi/shared/api_client.py", line 208, in __call_api return_data = self.deserialize(response_data, response_type, _check_type) File "/home/ubuntu/.pyenv/versions/3.8.10/envs/xxx/lib/python3.8/site-packages/pinecone/core/openapi/shared/api_client.py", line 301, in deserialize deserialized_data = validate_and_convert_types( File "/home/ubuntu/.pyenv/versions/3.8.10/envs/xxx/lib/python3.8/site-packages/pinecone/core/openapi/shared/model_utils.py", line 1441, in validate_and_convert_types converted_instance = attempt_convert_item( File "/home/ubuntu/.pyenv/versions/3.8.10/envs/xxx/lib/python3.8/site-packages/pinecone/core/openapi/shared/model_utils.py", line 1326, in attempt_convert_item raise get_type_error(input_value, path_to_item, valid_classes, key_type=key_type) pinecone.core.openapi.shared.exceptions.PineconeApiTypeError: Invalid type for variable 'received_data'. Required value type is IndexModel and passed type was str at ['received_data']`
> 
> any suggestions for this? thanks!

But, when I create the Pinecone instance by
`self.pc_cli = Pinecone(api_key=self.api_key, pool_threads=self.POOL_THREADS)`, i.e., dont pass the parameter: `host=self.host`, it's ok.
